### ISSUE TITLE
Incorporate additional utility functions (provided)

### ISSUE THREAD

**Issue by raineorshine** [coolaj86/semver-utils#3]
Would you be interested in incorporating some or all of the following functions into this repo? They are helpful for working with loose version numbers (e.g. "1", "1.2") and moving between them. This seems like an appropriate repo to locate them, although I could make a separate repo if not. If yes, I'll submit a pull request.

```
numParts
stringify
precisionAdd
getPrecision
setPrecision
addWildCard
```

https://github.com/tjunnone/npm-check-updates/commit/a5f0e238d4e44724784f7d3b5a0e7ee98329d172

**Comment by coolaj86** [comment]
Took me three years to notice this, but yeah, I think I'd like to see a PR if you're still interested.

Moved to https://git.coolaj86.com/coolaj86/semver-utils.js
